name: AnwesenCore
main: at.dietze.ac.Core
version: 1.0
author: lyxt
commands:
  setSpawn:
    description: lorem ipsum
  pointsystem:
    description: lorem ipsum
  getplaytime:
    description: lorem ipsum
  spawn:
    description: lorem ipsum
  setnick:
    description: lorem ipsum
  help:
    description: lorem ipsum